import { FormEvent, useEffect, useMemo, useState } from 'react';
import { createRoot } from 'react-dom/client';
import './styles.css';

type Status = 'Active' | 'Found' | 'Closed';
type Role = 'police' | 'public';
type Case = { id: string; name: string; age: string; location: string; contactPhone: string; status: Status; priority: 'High' | 'Standard'; reported: string; description: string; photoName?: string };
type View = 'dashboard' | 'report' | 'cases' | 'match' | 'public' | 'alerts' | 'analytics' | 'reports' | 'settings';
const seedCases: Case[] = [
  { id: 'MP-2026-0142', name: 'Aarav Sharma', age: '12', location: 'Hyderabad, Telangana', contactPhone: '+91 98765 43210', status: 'Active', priority: 'High', reported: 'Today', description: 'Last seen near Jubilee Hills at 4:30 PM.', photoName: 'aarav-sharma.jpg' },
  { id: 'MP-2026-0141', name: 'Meera Patel', age: '26', location: 'Pune, Maharashtra', contactPhone: '+91 98765 43211', status: 'Active', priority: 'Standard', reported: 'Yesterday', description: 'Wearing a blue jacket and carrying a black backpack.', photoName: 'meera-patel.jpg' },
  { id: 'MP-2026-0140', name: 'Kabir Khan', age: '9', location: 'Bengaluru, Karnataka', contactPhone: '+91 98765 43212', status: 'Found', priority: 'High', reported: '2 days ago', description: 'Safely reunited with family.', photoName: 'kabir-khan.jpg' },
];
const labels: Record<View, string> = { dashboard: 'Dashboard', report: 'Report missing', cases: 'Case details', match: 'Search & match', public: 'Public reports', alerts: 'Alerts', analytics: 'Analytics', reports: 'Results', settings: 'Settings' };

function App() {
  const [loggedIn, setLoggedIn] = useState(false), [role, setRole] = useState<Role>('police'), [view, setView] = useState<View>('dashboard'), [cases, setCases] = useState<Case[]>(() => { try { const saved = localStorage.getItem('missing-person-cases'); const parsed = saved ? JSON.parse(saved) : seedCases; return Array.isArray(parsed) ? parsed.map((item) => ({ ...item, contactPhone: item.contactPhone || 'Not provided' })) : seedCases; } catch { return seedCases; } }), [query, setQuery] = useState(''), [statusFilter, setStatusFilter] = useState<Status | 'All'>('All'), [selected, setSelected] = useState<Case | null>(null), [notice, setNotice] = useState(''), [matchFile, setMatchFile] = useState(''), [publicReports, setPublicReports] = useState(12);
  useEffect(() => { localStorage.setItem('missing-person-cases', JSON.stringify(cases)); }, [cases]);
  const active = cases.filter((item) => item.status === 'Active');
  const visible = useMemo(() => { const q = query.toLowerCase().trim(); return cases.filter((i) => (statusFilter === 'All' || i.status === statusFilter) && (!q || `${i.id} ${i.name} ${i.location}`.toLowerCase().includes(q))); }, [cases, query, statusFilter]);
  const navigate = (v: View) => { setView(v); setSelected(null); setNotice(''); };
  if (!loggedIn) return <Login onLogin={(selectedRole) => { setRole(selectedRole); setView(selectedRole === 'police' ? 'dashboard' : 'public'); setLoggedIn(true); }} />;
  const items: View[] = role === 'police' ? ['dashboard', 'report', 'cases', 'match', 'public', 'alerts', 'analytics', 'reports', 'settings'] : ['public', 'cases', 'match', 'reports', 'settings'];
  const publicLabels: Partial<Record<View, string>> = { public: 'Submit sighting', cases: 'Search persons', match: 'Photo match', reports: 'Results', settings: 'Settings' };
  return <main className="app-shell"><header className="topbar"><button className="brand" onClick={() => navigate(role === 'police' ? 'dashboard' : 'public')}><span>SF</span> Missing Person AI Tracker</button><nav>{items.map((i) => <button key={i} className={view === i ? 'active' : ''} onClick={() => navigate(i)}>{role === 'public' ? publicLabels[i] : labels[i]}</button>)}</nav><span className="role-label">{role === 'police' ? 'Police Officer' : 'Public / Parent'}</span><button className="logout" onClick={() => { setLoggedIn(false); navigate('dashboard'); }}>Log out</button></header>{notice && <div className="notice" role="status">{notice}<button onClick={() => setNotice('')}>×</button></div>}
    {view === 'dashboard' && <Dashboard cases={cases} navigate={navigate} />}
    {view === 'report' && <MissingForm onSave={(item) => { setCases([item, ...cases]); navigate('cases'); setNotice(`${item.name}'s case was saved.`); }} />}
    {view === 'cases' && (selected ? (role === 'police' ? <PoliceCaseDetails item={selected} onBack={() => setSelected(null)} onStatus={(status) => { setCases(cases.map((i) => i.id === selected.id ? { ...i, status } : i)); setSelected({ ...selected, status }); setNotice(`Case status updated to ${status}.`); }} onDelete={() => { setCases(cases.filter((i) => i.id !== selected.id)); setSelected(null); setNotice(`${selected.name}'s closed case was deleted.`); }} /> : <CaseDetails item={selected} readOnly onBack={() => setSelected(null)} onStatus={() => undefined} />) : <Cases cases={visible} query={query} setQuery={setQuery} statusFilter={statusFilter} setStatusFilter={setStatusFilter} onSelect={setSelected} />)}
    {view === 'match' && <Match cases={active} file={matchFile} setFile={setMatchFile} onOpen={(item) => { setSelected(item); setView('cases'); }} />}
    {view === 'public' && <PublicForm onSubmit={() => { setPublicReports(publicReports + 1); setNotice('Your sighting report was sent to the case team.'); }} />}
    {view === 'alerts' && <Alerts cases={active} onOpen={(item) => { setSelected(item); setView('cases'); }} />}
    {view === 'analytics' && <Analytics cases={cases} publicReports={publicReports} />}{view === 'reports' && <Reports cases={cases} publicReports={publicReports} />}
    {view === 'settings' && <Settings role={role} />}
  </main>;
}
function Login({ onLogin }: { onLogin: (role: Role) => void }) { const [role, setRole] = useState<Role>('police'); return <main className="login-page"><form className="login-card" onSubmit={(e) => { e.preventDefault(); onLogin(role); }}><div className="logo">MP</div><p className="eyebrow">Missing Person AI Tracker</p><h1>{role === 'police' ? 'Police Officer Login' : 'Public / Parent Login'}</h1><p>{role === 'police' ? 'Access the secure case-management system.' : 'Submit and follow up on a possible sighting.'}</p><div className="role-picker"><button type="button" className={role === 'police' ? 'selected' : ''} onClick={() => setRole('police')}>◉ Police Officer</button><button type="button" className={role === 'public' ? 'selected' : ''} onClick={() => setRole('public')}>♧ Parent / Family</button></div><label>Email Address<input type="email" defaultValue={role === 'police' ? 'officer@police.gov' : ''} required /></label><label>Password<input type="password" placeholder="Enter your password" required /></label>{role === 'police' && <label>Badge Number (optional)<input placeholder="e.g., MP001" /></label>}<button className="primary">{role === 'police' ? 'Sign in as Police Officer' : 'Sign in to Public Portal'}</button><small>Demo mode: any valid email and password works.</small></form></main> }
function Dashboard({ cases, navigate }: { cases: Case[]; navigate: (v: View) => void }) { const active = cases.filter((c) => c.status === 'Active').length; return <><section className="hero"><div><p className="eyebrow">Police officer workspace</p><h1>Dashboard overview</h1><p className="lede">Monitor active investigations, incoming sightings, and AI matching activity from one place.</p></div></section><section className="stats"><article><span>Total missing</span><strong>{cases.length}</strong><small>All registered cases</small></article><article><span>Active cases</span><strong>{active}</strong><small>Require investigation</small></article><article><span>Found cases</span><strong>{cases.filter((c) => c.status === 'Found').length}</strong><small>Successfully resolved</small></article><article><span>Recent sightings</span><strong>12</strong><small>Received this week</small></article></section><section className="dashboard-grid"><section className="panel dashboard-panel"><div className="module-title"><h2>Recent missing person cases</h2><button className="text-button" onClick={() => navigate('cases')}>View all cases</button></div>{cases.slice(0, 3).map((item) => <article className="case-row" key={item.id}><span className="avatar">{item.name.split(' ').map((n) => n[0]).join('')}</span><div><b>{item.name}</b><small>{item.id} · Age {item.age} · {item.location}</small><small>Reported {item.reported}</small></div><span className={`status ${item.status === 'Found' ? 'found' : ''}`}>{item.status}</span></article>)}</section><section className="panel dashboard-panel"><div className="module-title"><h2>AI matching activity</h2><button className="text-button" onClick={() => navigate('match')}>Open search</button></div><article className="activity blue"><b>Face recognition scan</b><p>CCTV comparison completed</p><small>95% match confidence</small></article><article className="activity green"><b>Location match found</b><p>Public sighting linked to an active case</p><small>Verified location signal</small></article><article className="activity orange"><b>Processing queue</b><p>New images ready for analysis</p><small>3 images pending review</small></article></section></section><section className="quick"><h2>Quick actions</h2><div><button onClick={() => navigate('report')}>Report missing person<br /><small>Create a new police case</small></button><button onClick={() => navigate('cases')}>Open case details<br /><small>Update status and case notes</small></button><button onClick={() => navigate('public')}>Review public reports<br /><small>Check community submissions</small></button></div></section></> }
function MissingForm({ onSave }: { onSave: (c: Case) => void }) { return <section className="form-panel"><p className="eyebrow">Missing person data</p><h1>Report a missing person</h1><form onSubmit={(e: FormEvent<HTMLFormElement>) => { e.preventDefault(); const d = new FormData(e.currentTarget); const photo = d.get('photo'); onSave({ id: `MP-2026-${String(Date.now()).slice(-4)}`, name: String(d.get('name')), age: String(d.get('age')), location: String(d.get('location')), contactPhone: String(d.get('contactPhone')), description: String(d.get('description')), priority: d.get('priority') === 'High' ? 'High' : 'Standard', status: 'Active', reported: 'Just now', photoName: photo instanceof File && photo.size ? photo.name : undefined }); }}><label>Full name<input name="name" required /></label><label>Age<input name="age" type="number" min="0" required /></label><label>Last known location<input name="location" required /></label><label>Contact phone number<input name="contactPhone" type="tel" inputMode="tel" placeholder="e.g., +91 98765 43210" required /></label><label>Priority<select name="priority"><option>Standard</option><option>High</option></select></label><label className="wide">Description<textarea name="description" required /></label><label className="wide">Photo<input name="photo" type="file" accept="image/*" /></label><button className="primary">Save missing-person case</button></form></section> }
function Cases({ cases, query, setQuery, statusFilter, setStatusFilter, onSelect }: { cases: Case[]; query: string; setQuery: (q: string) => void; statusFilter: Status | 'All'; setStatusFilter: (status: Status | 'All') => void; onSelect: (c: Case) => void }) { return <section className="panel"><div className="panel-head"><div><p className="eyebrow">Missing person data</p><h1>Case details</h1></div><div className="case-filters"><input value={query} onChange={(e) => setQuery(e.target.value)} placeholder="Search name, case ID, location" /><label>Case status<select value={statusFilter} onChange={(e) => setStatusFilter(e.target.value as Status | 'All')}><option value="All">All statuses</option><option>Active</option><option>Found</option><option>Closed</option></select></label></div></div><CaseTable cases={cases} onSelect={onSelect} /></section> }
function CaseTable({ cases, onSelect }: { cases: Case[]; onSelect: (c: Case) => void }) { return <div className="table-wrap"><table><thead><tr><th>Case</th><th>Location</th><th>Priority</th><th>Status</th><th /></tr></thead><tbody>{cases.map((i) => <tr key={i.id}><td><strong>{i.name}</strong><small>{i.id} · Age {i.age}</small></td><td>{i.location}</td><td><span className={`tag ${i.priority === 'High' ? 'high' : ''}`}>{i.priority}</span></td><td><span className={`status ${i.status === 'Found' ? 'found' : ''}`}>{i.status}</span></td><td><button className="text-button" onClick={() => onSelect(i)}>Open</button></td></tr>)}</tbody></table></div> }
function CaseDetails({ item, onBack, onStatus, readOnly }: { item: Case; onBack: () => void; onStatus: (s: Status) => void; readOnly: boolean }) { const phone = item.contactPhone || 'Not provided'; return <section className="detail panel"><button className="text-button" onClick={onBack}>← All cases</button><p className="eyebrow">{item.id}</p><h1>{item.name}</h1><div className="detail-grid"><p><b>Age</b>{item.age}</p><p><b>Last known location</b>{item.location}</p><p><b>Contact number</b>{phone === 'Not provided' ? phone : <a className="phone-link" href={`tel:${phone.replace(/[^+\d]/g, '')}`}>{phone}</a>}</p><p><b>Reported</b>{item.reported}</p><p><b>Priority</b>{item.priority}</p></div><h2>Case notes</h2><p>{item.description}</p>{readOnly ? <p className="public-note">Case information is view-only for public accounts. Contact the responsible police station with verified information.</p> : <label>Update case status<select value={item.status} onChange={(e) => onStatus(e.target.value as Status)}><option>Active</option><option>Found</option><option>Closed</option></select></label>}</section> }
function PoliceCaseDetails({ item, onBack, onStatus, onDelete }: { item: Case; onBack: () => void; onStatus: (s: Status) => void; onDelete: () => void }) { return <><CaseDetails item={item} onBack={onBack} onStatus={onStatus} readOnly={false} />{item.status === 'Closed' && <section className="delete-case-panel"><p>Only closed cases can be permanently removed from police records.</p><button className="danger-button" onClick={() => { if (window.confirm(`Delete the closed case for ${item.name}? This cannot be undone.`)) onDelete(); }}>Delete closed case</button></section>}</> }
const photoKey = (value: string) => value.toLowerCase().replace(/\.[^.]+$/, '').replace(/[^a-z0-9]/g, '');
function Match({ cases, file, setFile, onOpen }: { cases: Case[]; file: string; setFile: (v: string) => void; onOpen: (c: Case) => void }) {
  const matches = file ? cases.filter((item) => photoKey(item.photoName || item.name) === photoKey(file)) : [];
  return <section className="form-panel"><p className="eyebrow">AI-powered facial search</p><h1>Search & match</h1><p>Upload a clear image to find its related active case. Verify every result before acting.</p><label>Image to compare<input type="file" accept="image/*" onChange={(e) => setFile(e.target.files?.[0]?.name ?? '')} /></label>{file && <><div className="notice">Analysed <b>{file}</b>. {matches.length ? 'Related case matches are shown below.' : 'No related active case was found for this photo.'}</div>{matches.length > 0 && <CaseTable cases={matches} onSelect={onOpen} />}</>}</section>
}
function LiveMap({ cases }: { cases: Case[] }) { return <section className="map-page"><div className="panel map-heading"><div><p className="eyebrow">Investigation workspace</p><h1>Live sighting map</h1><p>Review active cases and reported sighting areas. Location data shown here is demonstration data.</p></div><button className="primary">Add search area</button></div><div className="map-layout"><section className="map-canvas"><span className="map-road r1" /><span className="map-road r2" /><span className="map-road r3" /><span className="map-pin pin-one">1</span><span className="map-pin pin-two">2</span><span className="map-pin pin-three">3</span><div className="map-legend"><b>Active investigation area</b><small>3 recent sighting markers</small></div></section><aside className="panel sighting-list"><p className="eyebrow">Active cases</p><h2>Nearby investigation leads</h2>{cases.map((item, index) => <article key={item.id}><span>{index + 1}</span><div><b>{item.name}</b><small>{item.location}</small><small>Last update: {item.reported}</small></div></article>)}</aside></div></section> }
function FaceScan() { const [file, setFile] = useState<File | null>(null); const [preview, setPreview] = useState(''); const onFile = (selected?: File) => { if (!selected) return; setFile(selected); setPreview(URL.createObjectURL(selected)); }; return <section className="form-panel scan-panel"><p className="eyebrow">Face-quality screening</p><h1>Face scan</h1><p>Upload a photo to prepare it for matching. MediaPipe Face Mesh can be connected here to verify that the image contains one clear, usable face.</p><label className="scan-drop">{preview ? <img src={preview} alt="Selected face preview" /> : <><b>Choose a photo</b><small>JPG, PNG or WEBP · front-facing image recommended</small></>}<input type="file" accept="image/*" onChange={(e) => onFile(e.target.files?.[0])} /></label>{file && <div className="scan-result"><span>✓</span><div><b>{file.name}</b><p>Ready for face detection. Run the scan to check pose, lighting, face count, and landmark quality.</p></div><button className="primary">Run face scan</button></div>}<p className="privacy-note">Only authorized personnel should upload sensitive images. A match is an investigative lead, not proof of identity.</p></section> }
function Timeline({ cases }: { cases: Case[] }) { return <section className="panel timeline-page"><p className="eyebrow">Case management</p><h1>Investigation timeline</h1><p className="report-note">A consolidated view of reporting, evidence, sightings, and review activity.</p><div className="timeline">{cases.slice(0, 3).map((item, index) => <article key={item.id}><span className={`timeline-dot dot-${index}`} /><div><small>{index === 0 ? 'Today · 10:30 AM' : index === 1 ? 'Yesterday · 4:15 PM' : '2 days ago · 9:00 AM'}</small><h2>{item.name}: case {index === 0 ? 'reviewed' : index === 1 ? 'sighting received' : 'status updated'}</h2><p>{index === 0 ? `Officer review started for ${item.id} near ${item.location}.` : index === 1 ? 'A community report and photograph were added for verification.' : 'The case record was updated with the latest family contact.'}</p></div></article>)}</div></section> }
function EvidenceVault() { const [files, setFiles] = useState<string[]>(['case-photo-aarav.jpg', 'public-sighting-102.jpg']); return <section className="panel evidence-page"><div className="panel-head"><div><p className="eyebrow">Secure case materials</p><h1>Evidence vault</h1><p className="report-note">Organize photos, videos, documents, and verified public submissions.</p></div><label className="primary upload-button">Upload evidence<input type="file" multiple onChange={(e) => setFiles([...files, ...Array.from(e.target.files ?? []).map((file) => file.name)])} /></label></div><div className="evidence-files">{files.map((file, index) => <article key={`${file}-${index}`}><span>{file.match(/\.(jpg|jpeg|png|webp)$/i) ? '▣' : '▤'}</span><div><b>{file}</b><small>{index < 2 ? 'Verified case material' : 'New upload · pending review'}</small></div><button className="text-button">Review</button></article>)}</div></section> }
function Settings({ role }: { role: Role }) { const [saved, setSaved] = useState(false); return <section className="panel settings-page"><p className="eyebrow">Account and application</p><h1>Settings</h1><p className="report-note">Manage your preferences for this {role === 'police' ? 'police officer' : 'public'} account.</p><form onSubmit={(e) => { e.preventDefault(); setSaved(true); }}><section><h2>Notifications</h2><label><input type="checkbox" defaultChecked /> Email me about case updates</label><label><input type="checkbox" defaultChecked={role === 'police'} /> Notify me about possible match alerts</label></section><section><h2>Display and privacy</h2><label>Preferred language<select defaultValue="English"><option>English</option><option>Hindi</option><option>Telugu</option></select></label><label>Data visibility<select defaultValue={role === 'police' ? 'Authorized officers' : 'Only my submissions'}><option>Authorized officers</option><option>Only my submissions</option></select></label></section><section><h2>Security</h2><label>Session timeout<select defaultValue="30 minutes"><option>15 minutes</option><option>30 minutes</option><option>1 hour</option></select></label><button type="button" className="text-button">Change password</button></section><button className="primary">Save settings</button>{saved && <span className="settings-saved">Settings saved for this browser session.</span>}</form></section> }
function PublicForm({ onSubmit }: { onSubmit: () => void }) { return <section className="form-panel"><p className="eyebrow">Community reporting</p><h1>Submit a sighting report</h1><p>Use this form only for a possible sighting. For an emergency, contact local emergency services.</p><form onSubmit={(e) => { e.preventDefault(); e.currentTarget.reset(); onSubmit(); }}><label>Location<input required /></label><label>Date and time<input type="datetime-local" required /></label><label className="wide">What did you see?<textarea required /></label><label className="wide">Photo (optional)<input type="file" accept="image/*" /></label><button className="primary">Send report</button></form></section> }
function Alerts({ cases, onOpen }: { cases: Case[]; onOpen: (i: Case) => void }) { return <section className="panel"><p className="eyebrow">Visualization alerts</p><h1>Priority alerts</h1>{cases.filter((i) => i.priority === 'High').map((i) => <article className="alert" key={i.id}><div><b>High-priority active case: {i.name}</b><p>{i.location} · reported {i.reported}</p></div><button className="text-button" onClick={() => onOpen(i)}>Review case</button></article>)}</section> }
function Analytics({ cases, publicReports }: { cases: Case[]; publicReports: number }) { const found = cases.filter((c) => c.status === 'Found').length; return <section className="panel"><p className="eyebrow">Analytics</p><h1>Case activity overview</h1><div className="chart"><div style={{ height: `${Math.max(cases.filter((c) => c.status === 'Active').length * 22, 10)}%` }}><span>{cases.filter((c) => c.status === 'Active').length}</span>Active</div><div style={{ height: `${Math.max(found * 35, 10)}%` }}><span>{found}</span>Found</div><div style={{ height: '75%' }}><span>{publicReports}</span>Reports</div></div></section> }
function Reports({ cases, publicReports }: { cases: Case[]; publicReports: number }) {
  const statuses: Status[] = ['Active', 'Found', 'Closed'];
  const caseResults = statuses.map((status) => ({ status, count: cases.filter((item) => item.status === status).length }));
  const largest = Math.max(...caseResults.map((item) => item.count), 1);
  const resolved = caseResults[1].count + caseResults[2].count;
  const resolvedPercent = cases.length ? Math.round((resolved / cases.length) * 100) : 0;
  return <section className="results-page">
    <div className="results-intro"><div><p className="eyebrow">System results</p><h1>All case results</h1><p>Live results from registered cases, paired with the completed 100-profile system test.</p></div><span className="live-pill">● Live dashboard data</span></div>
    <div className="result-summary">
      <article><span>Registered cases</span><b>{cases.length}</b><small>Updates as new cases are added</small></article>
      <article><span>Resolved cases</span><b>{resolved}</b><small>{resolvedPercent}% of current cases</small></article>
      <article><span>Community submissions</span><b>{publicReports}</b><small>Reports received for review</small></article>
      <article><span>Average processing</span><b>2.5<span>s</span></b><small>Report, match, and alert workflow</small></article>
    </div>
    <div className="results-layout">
      <section className="panel results-chart-card"><div className="module-title"><div><p className="eyebrow">Case distribution</p><h2>Current case status</h2></div><span className="chart-total">{cases.length} total</span></div><div className="horizontal-chart">{caseResults.map((item) => <div className="chart-row" key={item.status}><div className="chart-label"><span className={`dot ${item.status.toLowerCase()}`} />{item.status}</div><div className="track"><div className={`fill ${item.status.toLowerCase()}`} style={{ width: `${(item.count / largest) * 100}%` }} /></div><b>{item.count}</b></div>)}</div><p className="chart-caption">The chart changes automatically when a case is created or its status is updated.</p></section>
      <section className="panel test-score"><p className="eyebrow">Matching validation</p><h2>92% identification accuracy</h2><div className="score-ring"><span>92<small>%</small></span></div><p>Known-result tests matched profiles using facial-image similarity, age, and location filters.</p><small>Dataset: 100 simulated missing-person profiles</small></section>
    </div>
    <section className="panel result-evidence"><div className="module-title"><div><p className="eyebrow">Implementation outcome</p><h2>End-to-end result summary</h2></div><span className="verified">✓ Tested</span></div><div className="evidence-grid"><article><span className="evidence-icon">✓</span><div><b>Validated case reporting</b><p>Required-field checks help families submit complete, accurate reports quickly.</p></div></article><article><span className="evidence-icon">▣</span><div><b>Photos and data processed</b><p>Uploaded images and case details are stored and displayed in the relevant dashboards.</p></div></article><article><span className="evidence-icon">↗</span><div><b>Real-time match alerts</b><p>Possible matches create immediate alerts so administrators can review them.</p></div></article><article><span className="evidence-icon">◌</span><div><b>Responsive user portals</b><p>Family and authority dashboards support case tracking, reports, and notifications on desktop and mobile.</p></div></article></div></section>
  </section>
}
const root = document.getElementById('root'); if (!root) throw new Error('Application root element was not found.'); createRoot(root).render(<App />);
